sudo: required
language: generic
services:
- docker
before_script:
- docker build -t lukasmartinelli/hadolint .
script:
- docker run --rm lukasmartinelli/hadolint bash -c 'cabal configure --enable-tests && cabal test'
- docker run --rm lukasmartinelli/hadolint bash integration_test.sh
