sudo: required
language: generic
services:
- docker
before_script:
- docker build -t lukasmartinelli/hadolint .
script:
- docker run --rm lukasmartinelli/hadolint cabal test
- docker run --rm lukasmartinelli/hadolint hlint --ignore "Eta reduce" --ignore "Use string literal" src
- docker run --rm lukasmartinelli/hadolint bash integration_test.sh
