# Build starts faster without `sudo`
sudo: false

language: c
compiler: gcc

cache:
  directories:
  - $HOME/.stack
  timeout: 300

# Increase depth (from default 50) to preserve version from `git describe`
git:
  depth: 100

matrix:
  include:
    - env: &lts-fixed ARGS=""
      os: linux
      arch: arm64
      addons:
        artifacts: {paths: [./releases]}
      before_deploy:
        # Show dynamic libraries `hadolint` depends on
        - ldd $(which hadolint) || true
        - curl -sSL https://github.com/upx/upx/releases/download/v3.96/upx-3.96-arm64_linux.tar.xz
          | tar -x --xz --strip-components=1 -C ~/.local/bin upx-3.96-arm64_linux/upx
        # Compress binary
        - upx -q --best --ultra-brute "./releases/${BINARY_NAME}"
      deploy: &release_deploy
        provider: releases
        api_key:
          secure: bAcEdQB7Hk4yDz58u5oo8aEoitbbobaqW7Dr58asJHnm0KG3g1lJqCrgRP2ldbmG8I9zj1osfw0qGCNc3MZW2sV5AaWqxUGC1Sw2jmz0fqdajk8f0bZXZMECFeryPeXmPRftw0VAKz5dVw5wzjunaAVUEuCC3B4a80v/3+Qj8t2FaslG+uNoTTEEzHPfwgowYPQf+QR1Ob3lWM41g0ORC9mgYAD/PIUi8mnxCVRExUecHwhTM1A8UMo/MDVQuv3cclJ+Xc10O9KTCr7tf9uh4g2ZY4RD/aW5zuUt1tqMVJfcL/BQi5wOrhJd0jwMW8LZg0eBypezXZ70CC1Eb+vwe7OUrDlUroyzPUsOXd7u6LAWe+dBE0zNwvWXFnUF6ls8cJDhrVoSmVV3SFd208/xmemDgMmtBWwcjxyCM3kMyCBx1T6nkXQ4czS5Nvn1dav87sgyowR52W52oiyomJyJtBrmrlP/2qgNAJgQuzah/ltuBBvyGCaiwFQFHzUjUNv/ENCNP06aEVTLdbkLXLNfvlw6NZbn8KIOGFmSncLT3hNtcRhS6XnrCIyOc6hYelzVLXPNhmWFo7Ob3/1GFSvlWVmzHEp5+AeTYAQmsAZMAe/E5ofVSrU/3DhXvxMjzdOq5bZ9FsOMfooxYIPp05kVsW4H6dB8kIUqQcWTntt4ys4=
        file: "./releases/${BINARY_NAME}"
        skip_cleanup: true
        draft: true
        tag_name: "${TRAVIS_TAG}"
        on:
          tags: true

before_install:
  - export BINARY_NAME="hadolint-$(uname -s)-$(uname -m)"
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - |
    if [[ "${TRAVIS_OS_NAME}" = "osx" ]]
    then
      travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 \
        | tar xz --strip-components=1 -C ~/.local/bin --include   '*/stack'
    else
      travis_retry curl -sSL https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64 \
        | tar xz --strip-components=1 -C ~/.local/bin --wildcards '*/stack'
    fi

install:
  - travis_retry stack --no-terminal --install-ghc $ARGS test --only-dependencies
  - stack --no-terminal $ARGS install --ghc-options='-fPIC' --flag hadolint:static

script:
  - stack --no-terminal $ARGS test
  - hadolint docker/Dockerfile

after_success:
  - mkdir -p ./releases/
  - cp "$(which hadolint)" "./releases/${BINARY_NAME}"
