name: hadolint
version: '1.6.1'
synopsis: Dockerfile Linter JavaScript API
description: A smarter Dockerfile linter that helps you build best practice Docker images.
category: Development
author: Lukas Martinelli
maintainer: me@lukasmartinelli.ch
copyright: Lukas Martinelli
license: GPL-3
homepage: https://github.com/hadolint/hadolint
git: git@github.com:hadolint/hadolint.git
extra-source-files: README.md
dependencies:
  - base >=4.8 && <5
  - parsec >=3.1
  - language-docker >=3.0.0
library:
  source-dirs: src
  exposed-modules:
    - Hadolint.Bash
    - Hadolint.Rules
    - Hadolint.Formatter.Format
    - Hadolint.Formatter.Json
    - Hadolint.Formatter.TTY
    - Hadolint.Formatter.Codeclimate
    - Hadolint.Formatter.Checkstyle
  dependencies:
    - &bytestring bytestring >=0.10
    - &split split >=0.2
    - &ShellCheck ShellCheck >=0.4.7
    - aeson
    - text
    - bytestring
    - dlist
executables:
  hadolint:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hadolint
      - optparse-applicative
      - gitrev >=1.3.1
      - filepath
      - directory >= 1.3.0
      - yaml
    when:
    # OS X does not support static build https://developer.apple.com/library/content/qa/qa1118
    - condition: '!(os(osx))'
      ld-options:
        - -static
        - -pthread
tests:
  hadolint-unit-tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - *bytestring
      - *split
      - *ShellCheck
      - aeson
      - HUnit >=1.2
      - hspec
      - hadolint
