# Runs on pull requests against master

name: linux

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/linux.yml'
      - 'stack*.yaml'
      - 'app/**'
      - 'src/**'
      - 'test/**'
      # ignore changes to example files, though currently some func tests depend on them
      - 'README.md'

jobs:
  hadolint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: macos-latest
        - os: ubuntu-latest

    steps:

    # setup:

    - name: Check out
      uses: actions/checkout@v2


    - name: Setup Stack
      uses: actions/setup-haskell@v1.1.4
      with:
        enable-stack: true
        stack-version: 'latest'

    # cache

    - name: Cache stack global package db
      id:   stack-global
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-global
    - name: Cache stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache@v2
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-programs
    - name: Cache .stack-work
      uses: actions/cache@v2
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-work

    #actions

    - name: Build
      run: stack build --test

    - name: Test
      run: stack test

