# Runs on pull requests against master

name: Build and Test

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/pull_request.yml'
      - 'stack*.yaml'
      - 'hadolint.cabal'
      - 'app/**'
      - 'src/**'
      - 'test/**'
      - 'README.md'

jobs:
  hadolint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
        - os: ubuntu-latest
        - os: windows-latest

    steps:

    # setup:

    - name: Check out
      uses: actions/checkout@v2


    - name: Setup Haskell
      id: setup-haskell-cabal
      uses: actions/setup-haskell@v1.1.4

    - name: Freeze
      run: cabal freeze

    # cache

    - name: Cache store
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}

    #actions

    - name: Test
      run: cabal test --enable-tests --test-show-details=direct


  hlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HLINT_ACTION_LOG_LEVEL: debug
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Haskell Linter
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  remark-lint:
    name: remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remark-lint
        run: |
          docker pull zemanlx/remark-lint:0.1.4
          docker run --rm -i -v $PWD:/lint/input:ro zemanlx/remark-lint:0.1.4 --frail .
